var netflixSeries = [
  {
    backdrop_path: "/35SS0nlBhu28cSe7TiO3ZiywZhl.jpg",
    first_air_date: "2018-05-02",
    genre_ids: [10759, 18],
    id: 77169,
    name: "Cobra Kai",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Cobra Kai",
    overview:
      "Esta sequência de Karate Kid pega 30 anos depois dos eventos do All Valley Karate Tournament de 1984 e encontra Johnny Lawrence em busca de redenção reabrindo o infame dojo de karate Cobra Kai . Isso reacende sua antiga rivalidade com o bem-sucedido Daniel LaRusso, que vem trabalhado para manter o equilíbrio em sua vida sem o seu mentor Miyagi.",
    popularity: 1083.212,
    poster_path: "/5qMupAz4A9EN5Rutrkmov45mNXZ.jpg",
    vote_average: 8.2,
    vote_count: 4213,
  },
  {
    backdrop_path: "/ktDJ21QQscbMNQfPpZBsNORxdDx.jpg",
    first_air_date: "2016-01-25",
    genre_ids: [80, 10765],
    id: 63174,
    name: "Lucifer",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Lucifer",
    overview:
      "Entediado com a vida nas trevas, o diabo se muda para Los Angeles, abre um piano-bar e empresta sua sabedoria a uma investigadora de assassinatos.",
    popularity: 1065.985,
    poster_path: "/hdKxcoV5CFc3sGOmbGXDXbx1cTZ.jpg",
    vote_average: 8.5,
    vote_count: 11394,
  },
  {
    backdrop_path: "/qw3J9cNeLioOLoR68WX7z79aCdK.jpg",
    first_air_date: "2021-09-17",
    genre_ids: [10759, 9648, 18],
    id: 93405,
    name: "Round 6",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Centenas de jogadores falidos aceitam um estranho convite para um jogo de sobrevivência. Um prêmio milionário aguarda, mas as apostas são altas e mortais.",
    popularity: 847.958,
    poster_path: "/6gcHdboppvplmBWxvROc96NJnmm.jpg",
    vote_average: 7.8,
    vote_count: 9993,
  },
  {
    backdrop_path: "/2Gj7RRFnM4dWVp9p5RpN09E67PJ.jpg",
    first_air_date: "2016-06-02",
    genre_ids: [80, 18],
    id: 67166,
    name: "El marginal",
    origin_country: ["AR"],
    original_language: "es",
    original_name: "El marginal",
    overview: "",
    popularity: 641.774,
    poster_path: "/p1GFsUK5nCVHYNtjRxoGyfGdD9C.jpg",
    vote_average: 8.3,
    vote_count: 216,
  },
  {
    backdrop_path: "/9hNJ3fvIVd4WE3rU1Us2awoTpgM.jpg",
    first_air_date: "2021-12-24",
    genre_ids: [18, 10765],
    id: 96777,
    name: "O Mar da Tranquilidade",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "고요의 바다",
    overview:
      "Em uma missão perigosa na Lua, exploradores espaciais tentam recuperar amostras em uma estação de pesquisa abandonada e repleta de segredos.",
    popularity: 707.478,
    poster_path: "/tF4dl94nLabniP1TDeGa61OZTQI.jpg",
    vote_average: 8,
    vote_count: 253,
  },
  {
    backdrop_path: "/8Xs20y8gFR0W9u8Yy9NKdpZtSu7.jpg",
    first_air_date: "2022-01-28",
    genre_ids: [18, 10765],
    id: 99966,
    name: "All of Us Are Dead",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "지금 우리 학교는",
    overview:
      "Uma epidemia mortal surge em uma escola. Encurralados, os alunos só tem uma opção: lutar com todas as forças para não virarem zumbis.",
    popularity: 801.048,
    poster_path: "/s1ZL8Jwc72QUTjdvniBmmf0VBdL.jpg",
    vote_average: 8.4,
    vote_count: 193,
  },
  {
    backdrop_path: "/5npLowyLY2fqUpyAOq2x0bXwwIv.jpg",
    first_air_date: "2022-01-05",
    genre_ids: [18],
    id: 134949,
    name: "Rebelde",
    origin_country: ["MX"],
    original_language: "es",
    original_name: "Rebelde",
    overview:
      "No colégio, começa o novo ano escolar, mas uma sociedade secreta ameaça os sonhos musicais dos alunos.",
    popularity: 507.887,
    poster_path: "/jRlI5euugVZR6a1Ptt0nSWeiWH.jpg",
    vote_average: 7.4,
    vote_count: 177,
  },
  {
    backdrop_path: "/yqbTWmaP4fdnrbgwPQDHITktyOE.jpg",
    first_air_date: "2019-01-11",
    genre_ids: [35, 18],
    id: 81356,
    name: "Sex Education",
    origin_country: ["GB"],
    original_language: "en",
    original_name: "Sex Education",
    overview:
      "O inseguro Otis manja tudo quando o negócio é aconselhamento sexual, graças à sua mãe sexóloga. E aí a rebelde Maeve propõe criar uma clínica de terapia sexual na escola.",
    popularity: 497.355,
    poster_path: "/cK6JhcZFpwVW9tldz3llodY2TeY.jpg",
    vote_average: 8.4,
    vote_count: 5350,
  },
  {
    backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    first_air_date: "2017-05-02",
    genre_ids: [80, 18],
    id: 71446,
    name: "La Casa de Papel",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "La Casa de Papel",
    overview:
      "Um homem misterioso que atende pelo nome de El Profesor, está planejando o maior assalto do século. A fim de realizar o ambicioso plano ele recruta uma gangue de oito pessoas com certas habilidades que não tem nada a perder. O objetivo é infiltrar na Casa da Moeda, de modo que eles possam imprimir 2,4 bilhões de euros. Para fazer isso eles precisam de onze dias de reclusão, durante o qual eles vão ter que lidar com sessenta e sete reféns e as forças da Polícia de Elite, com cenas de muita ação e planos brilhantes de El Profesor.",
    popularity: 484.664,
    poster_path: "/qUmlmYWx3WndM01DHOTrmeiklVW.jpg",
    vote_average: 8.3,
    vote_count: 15975,
  },
  {
    backdrop_path: "/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
    first_air_date: "2019-12-20",
    genre_ids: [10765, 18, 10759],
    id: 71912,
    name: "The Witcher",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Witcher",
    overview:
      "O mutante Geralt de Rívia é um caçador de monstros que luta para encontrar seu lugar num mundo onde as pessoas muitas vezes são mais perversas que as criaturas selvagens.",
    popularity: 438.722,
    poster_path: "/e5iqR3k7azXGK1tGaOLMnKycGku.jpg",
    vote_average: 8.2,
    vote_count: 3386,
  },
  {
    backdrop_path: "/ikN8ABD9pXHuW4JFqTEHr3ae8rd.jpg",
    first_air_date: "2021-11-19",
    genre_ids: [18, 80, 9648, 10765],
    id: 106651,
    name: "Profecia do Inferno",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "지옥",
    overview:
      "Quando o mundo é invadido por criaturas sobrenaturais que condenam as pessoas ao inferno, um grupo religioso afirma ser a justiça divina.",
    popularity: 442.576,
    poster_path: "/wmb0qvVKIU4dFtPRopbx594Zzck.jpg",
    vote_average: 7.6,
    vote_count: 439,
  },
  {
    backdrop_path: "/gD830J0sf5gEeZvzkRVPdGxJmSR.jpg",
    first_air_date: "2017-07-21",
    genre_ids: [80, 18],
    id: 69740,
    name: "Ozark",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Ozark",
    overview:
      "Um consultor financeiro se muda com a família para as montanhas do Missouri com o objetivo de lavar quinhentos milhões de dólares e acalmar um violento traficante.",
    popularity: 364.447,
    poster_path: "/epUO5w9nRmozR0iWCFwChT3ha6j.jpg",
    vote_average: 8.2,
    vote_count: 1241,
  },
  {
    backdrop_path: "/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg",
    first_air_date: "2021-11-06",
    genre_ids: [16, 10765, 10759, 18],
    id: 94605,
    name: "Arcane",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Arcane",
    overview:
      "Em meio ao conflito entre as cidades-gêmeas de Piltover e Zaun, duas irmãs lutam em lados opostos de uma guerra entre tecnologias mágicas e convicções incompatíveis.",
    popularity: 382.357,
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    vote_average: 9.1,
    vote_count: 1634,
  },
  {
    backdrop_path: "/hNj7EzEQyttoPBpYlLTkATnIiab.jpg",
    first_air_date: "2018-10-05",
    genre_ids: [80, 9648, 18],
    id: 76669,
    name: "Elite",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Élite",
    overview:
      "Após três jovens da escola pública serem transferidos para um conceituado colégio de elite, o conflito entre classes acaba levando a um assassinato.",
    popularity: 318.76,
    poster_path: "/4Ez5MVtC3N7cMV6LDqgZvKrwp5U.jpg",
    vote_average: 8.1,
    vote_count: 7848,
  },
  {
    backdrop_path: "/jo6eCDDH1RrKsZlqXmxA1BKxcYJ.jpg",
    first_air_date: "2021-12-20",
    genre_ids: [9648, 35],
    id: 137570,
    name: "Élite Historias Breves: Samuel Omar",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Élite Historias Breves: Samuel Omar",
    overview:
      "Agora que está em remissão, Ander quer passar o verão ajudando seu parceiro de quimioterapia, Alexis, a enfrentar o tratamento.",
    popularity: 177.797,
    poster_path: "/r9n8JnlM6k8ZeYSyIzlFmikLEfY.jpg",
    vote_average: 7.3,
    vote_count: 29,
  },
  {
    backdrop_path: "/rcA17r3hfHtRrk3Xs3hXrgGeSGT.jpg",
    first_air_date: "2016-07-15",
    genre_ids: [10765, 9648, 18],
    id: 66732,
    name: "Stranger Things",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.",
    popularity: 280.904,
    poster_path: "/jUrDkXkVXe5cDIYA7Ss81P1CvtX.jpg",
    vote_average: 8.6,
    vote_count: 9321,
  },
  {
    backdrop_path: "/gLACGQiS8kRP2hDnzdmIYo2uRRc.jpg",
    first_air_date: "2015-04-10",
    genre_ids: [80, 18, 10759],
    id: 61889,
    name: "Marvel - Demolidor",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Marvel's Daredevil",
    overview:
      "Cego desde pequeno, Matt Murdock luta contra a injustiça durante o dia como advogado e à noite nas ruas de Hell’s Kitchen, Nova York.",
    popularity: 265.24,
    poster_path: "/vNbGwybrD2vEc3asMTF36W0bVds.jpg",
    vote_average: 8,
    vote_count: 2934,
  },
  {
    backdrop_path: "/4tYspgwxmK2XRjhi71tuY6R2iGv.jpg",
    first_air_date: "2020-07-15",
    genre_ids: [9648, 18],
    id: 105214,
    name: "Desejo Sombrio",
    origin_country: ["MX"],
    original_language: "es",
    original_name: "Oscuro deseo",
    overview:
      "Casada, Alma passa um fim de semana fora de casa. A experiência desperta uma paixão, mas acaba em tragédia e a faz questionar a verdade sobre as pessoas próximas.",
    popularity: 292.113,
    poster_path: "/7nBrKoiH3vXFQtxJmM3v5cRMdpj.jpg",
    vote_average: 7.3,
    vote_count: 3660,
  },
  {
    backdrop_path: "/eAZtz2ydxBaHtJw3J42Gdy2DSpc.jpg",
    first_air_date: "2021-01-20",
    genre_ids: [35, 18],
    id: 115857,
    name: "Mãe Só Tem Duas",
    origin_country: ["MX"],
    original_language: "es",
    original_name: "Madre solo hay dos",
    overview:
      "Depois de descobrirem que seus bebês foram trocados na maternidade, duas mulheres acham uma saída inusitada: formar uma família.",
    popularity: 261.712,
    poster_path: "/v3S0wWlKharBKR0kHHof7uRXq9H.jpg",
    vote_average: 7.5,
    vote_count: 1044,
  },
  {
    backdrop_path: "/9nBVkNBe4x9HKDAzxjxlIqecxCW.jpg",
    first_air_date: "2021-06-25",
    genre_ids: [18],
    id: 126280,
    name: "Sex/Life",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Sex/Life",
    overview:
      "Uma mulher casada e mãe de dois filhos não consegue parar de pensar no passado tórrido com o ex.",
    popularity: 263.785,
    poster_path: "/kfcJl5e8CRWDU7e4vX6uNABPRbS.jpg",
    vote_average: 7.2,
    vote_count: 857,
  },
];
var netflixMovies = [
  {
    adult: false,
    backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker é desmascarado e não consegue mais separar sua vida normal dos grandes riscos de ser um super-herói. Quando ele pede ajuda ao Doutor Estranho, os riscos se tornam ainda mais perigosos, e o forçam a descobrir o que realmente significa ser o Homem-Aranha.",
    popularity: 21676.527,
    poster_path: "/fVzXp3NwovUlLe7fvoRynCmBPNc.jpg",
    release_date: "2021-12-15",
    title: "Homem-Aranha: Sem Volta Para Casa",
    video: false,
    vote_average: 8.4,
    vote_count: 6699,
  },
  {
    adult: false,
    backdrop_path: "/k2twTjSddgLc1oFFHVibfxp2kQV.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 524434,
    original_language: "en",
    original_title: "Eternals",
    overview:
      'Após os eventos de "Vingadores: Ultimato", os Eternos, uma raça alienígena imortal criada pelos Celestiais que vivem em segredo na Terra há mais de 7000 anos, se reúnem após uma tragédia inesperada para proteger a humanidade de seus colegas malignos: os Deviantes.',
    popularity: 5660.794,
    poster_path: "/mzezdUZEnpiUIlxpdyLO1R08Lqm.jpg",
    release_date: "2021-11-03",
    title: "Eternos",
    video: false,
    vote_average: 7.2,
    vote_count: 3823,
  },
  {
    adult: false,
    backdrop_path: "/m3Ys7UDzUzOyoPYKzp4GhKKokUr.jpg",
    genre_ids: [16, 10751, 14, 35, 12],
    id: 585083,
    original_language: "en",
    original_title: "Hotel Transylvania: Transformania",
    overview:
      "Drac e sua turma acabam sendo transformados em humanos após uma invenção de Van Helsing. Agora, eles precisam viajar até a Floresta Amazônica para encontrar o que pode ser a única solução para reverter a transformação, antes que seus poderes se percam para sempre.",
    popularity: 4795.881,
    poster_path: "/9PbtCo5IIkd26WPQfZUpPyn6fTz.jpg",
    release_date: "2022-01-13",
    title: "Hotel Transilvânia: Transformonstrão",
    video: false,
    vote_average: 7.6,
    vote_count: 1370,
  },
  {
    adult: false,
    backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 568124,
    original_language: "en",
    original_title: "Encanto",
    overview:
      "Uma garota chamada Mirabel Madrigal cresce como o único membro não mágico de sua família, que vivem escondidos em uma vibrante casa encantada nas montanhas da Colômbia.",
    popularity: 4395.662,
    poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    release_date: "2021-11-24",
    title: "Encanto",
    video: false,
    vote_average: 7.8,
    vote_count: 3726,
  },
  {
    adult: false,
    backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
    genre_ids: [35, 16, 10751, 10402],
    id: 438695,
    original_language: "en",
    original_title: "Sing 2",
    overview:
      "Buster Moon e seus amigos devem persuadir o recluso astro do rock Clay Calloway a se juntar a eles para a abertura de um novo show.",
    popularity: 3212.515,
    poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
    release_date: "2021-12-01",
    title: "Sing 2",
    video: false,
    vote_average: 8.3,
    vote_count: 1532,
  },
  {
    adult: false,
    backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
    genre_ids: [35, 14, 12],
    id: 425909,
    original_language: "en",
    original_title: "Ghostbusters: Afterlife",
    overview:
      "Uma mãe solteira resolve se mudar para uma pequena cidade do interior com seus filhos, e acaba descobrindo uma conexão com os Caça-Fantasmas originais e o que o seu avô deixou para trás como legado.",
    popularity: 2803.12,
    poster_path: "/719aIhGrTrJ0yzkZ806Ea4rbonV.jpg",
    release_date: "2021-11-11",
    title: "Ghostbusters: Mais Além",
    video: false,
    vote_average: 7.7,
    vote_count: 1693,
  },
  {
    adult: false,
    backdrop_path: "/t4To8feUSysyBs4tlBAbXIrKlCv.jpg",
    genre_ids: [28, 53],
    id: 860623,
    original_language: "en",
    original_title: "Last Man Down",
    overview:
      "Depois que a civilização sucumbe a uma pandemia mortal e sua esposa é assassinada, um soldado das forças especiais abandona seu dever e se torna um eremita na selva nórdica. Anos depois, uma mulher ferida aparece em sua porta. Ela escapou de um laboratório e seus perseguidores acreditam que seu sangue é a chave para uma cura mundial. Ele hesita em se envolver, mas todas as dúvidas são deixadas de lado quando ele descobre que seu perseguidor não é outro senão o comandante Stone, o homem que assassinou sua esposa alguns anos atrás.",
    popularity: 3359.778,
    poster_path: "/zBQFWjOIE3hoYCG67Y3VVaSnLyc.jpg",
    release_date: "2021-10-19",
    title: "Pandemia: A Guerra Final",
    video: false,
    vote_average: 6.7,
    vote_count: 164,
  },
  {
    adult: false,
    backdrop_path: "/srJ7haOhfykoPOYPQrstOaFem08.jpg",
    genre_ids: [28],
    id: 811592,
    original_language: "en",
    original_title: "One Shot",
    overview:
      "Em um esforço para evitar um ataque terrorista em Washington D.C., um esquadrão de elite de SEALs da Marinha liderado pelo tenente Jake Harris e uma analista júnior da CIA Zoe Anderson deve resgatar um prisioneiro de uma prisão em uma ilha secreta da CIA. As tensões aumentam quando o vice-gerente do local, Jack Yorke, se recusa a libertar o suspeito terrorista com base apenas nas informações de Anderson, mas quando a base é atacada por ondas de insurgentes, eles devem se unir para completar a missão.",
    popularity: 3304.357,
    poster_path: "/2LSwzrdj7ljnFhiqIgfp9rd46fU.jpg",
    release_date: "2021-11-05",
    title: "Tiro Certo",
    video: false,
    vote_average: 6.8,
    vote_count: 147,
  },
  {
    adult: false,
    backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
    genre_ids: [27, 28, 878],
    id: 460458,
    original_language: "en",
    original_title: "Resident Evil: Welcome to Raccoon City",
    overview:
      "O que já foi um dia a casa da gigante farmacêutica em expansão Umbrella Corporation, Raccoon City, é agora uma cidade agonizante do meio-oeste. O êxodo da empresa transformou a cidade em um deserto, com um grande mal fermentando escondido abaixo da superfície. Quando esse mal é libertado, um grupo de sobreviventes deve trabalhar juntos para descobrir a verdade por trás da Umbrella enquanto buscam viver por mais uma noite.",
    popularity: 2465.751,
    poster_path: "/tnKi8Vx9mRvOGrmzBOOh5wHEbQI.jpg",
    release_date: "2021-11-24",
    title: "Resident Evil: Bem-Vindo a Raccoon City",
    video: false,
    vote_average: 6.1,
    vote_count: 1073,
  },
  {
    adult: false,
    backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
    genre_ids: [878, 28, 12],
    id: 624860,
    original_language: "en",
    original_title: "The Matrix Resurrections",
    overview:
      "Em um mundo de duas realidades — a vida cotidiana e o que está por trás dela —, Thomas Anderson terá que escolher seguir o coelho branco mais uma vez. A escolha, embora seja uma ilusão, ainda é a única maneira de entrar ou sair da Matrix, que é mais forte, mais segura e mais perigosa do que nunca.",
    popularity: 2459.501,
    poster_path: "/9DT4WVqZqBEI9Kub18gZ3m1D89m.jpg",
    release_date: "2021-12-16",
    title: "Matrix Resurrections",
    video: false,
    vote_average: 6.8,
    vote_count: 2655,
  },
  {
    adult: false,
    backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
    genre_ids: [878, 28, 12],
    id: 580489,
    original_language: "en",
    original_title: "Venom: Let There Be Carnage",
    overview:
      "Em busca de seu próximo furo de reportagem, o jornalista Eddie Brock consegue uma entrevista exclusiva com Cletus Kasady, um assassino no corredor da morte, que descobre o segredo de Eddie e se torna o hospedeiro de Carnificina, um simbionte aterrorizante e ameaçador. Eddie e Venom precisam superar sua relação atribulada e trabalhar em conjunto para derrotar Carnificina.",
    popularity: 2338.164,
    poster_path: "/h5UzYZquMwO9FVn15R2eK2itmHu.jpg",
    release_date: "2021-09-30",
    title: "Venom: Tempo de Carnificina",
    video: false,
    vote_average: 7.1,
    vote_count: 6101,
  },
  {
    adult: false,
    backdrop_path: "/2Jp2RIwJ3Dt7vamkTt7llVJ7uY.jpg",
    genre_ids: [53, 9648, 18],
    id: 916740,
    original_language: "en",
    original_title: "Brazen",
    overview:
      "A escritora de livros de mistério Grace Miller é famosa pelo instinto para resolver crimes e vai precisar de todo esse talento para investigar o assassinato da irmã.",
    popularity: 2079.991,
    poster_path: "/A5v6Wi7lYR3a9m6CzntZWAcGFGV.jpg",
    release_date: "2022-01-13",
    title: "Indecente",
    video: false,
    vote_average: 4.8,
    vote_count: 168,
  },
  {
    adult: false,
    backdrop_path: "/dK12GIdhGP6NPGFssK2Fh265jyr.jpg",
    genre_ids: [28, 35, 80, 53],
    id: 512195,
    original_language: "en",
    original_title: "Red Notice",
    overview:
      "No mundo do crime internacional, a INTERPOL lança um Alerta Vermelho, o que inicia uma caçada para capturar a mais notória ladra de artes do globo.",
    popularity: 1791.409,
    poster_path: "/pe17f8VDfzbvbHSAKAlcORtBHmW.jpg",
    release_date: "2021-11-04",
    title: "Alerta Vermelho",
    video: false,
    vote_average: 6.8,
    vote_count: 2859,
  },
  {
    adult: false,
    backdrop_path: "/AmLpWYm9R3Ur2FLPgj5CH3wR8wp.jpg",
    genre_ids: [878, 53],
    id: 739413,
    original_language: "en",
    original_title: "Mother/Android",
    overview:
      "Em um mundo pós-apocalíptico assolado pela revolta dos androides, uma jovem grávida e o namorado buscam desesperadamente um lugar seguro.",
    popularity: 1415.432,
    poster_path: "/hfEuG7GkU2LOiT2O32OEfynRJqV.jpg",
    release_date: "2021-12-17",
    title: "Mãe x Androides",
    video: false,
    vote_average: 5.8,
    vote_count: 350,
  },
  {
    adult: false,
    backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
    genre_ids: [28, 12, 14],
    id: 566525,
    original_language: "en",
    original_title: "Shang-Chi and the Legend of the Ten Rings",
    overview:
      "Shang-Chi precisa confrontar o passado que pensou ter deixado para trás. Ao mesmo tempo, ele é envolvido em uma teia de mistérios da organização conhecida como Dez Anéis.",
    popularity: 1410.508,
    poster_path: "/ArrOBeio968bUuUOtEpKa1teIh4.jpg",
    release_date: "2021-09-01",
    title: "Shang-Chi e a Lenda dos Dez Anéis",
    video: false,
    vote_average: 7.8,
    vote_count: 5429,
  },
  {
    adult: false,
    backdrop_path: "/mo57hzhW3BcZL1f7MNteWKHsmlN.jpg",
    genre_ids: [28, 53],
    id: 763788,
    original_language: "en",
    original_title: "Dangerous",
    overview:
      "Um sociopata reformado vai para uma ilha remota após a morte de seu irmão. Logo após sua chegada, a ilha cai sob o cerco de uma gangue mortal de mercenários, e quando ele descobre seu papel na morte de seu irmão, ele parte em uma busca implacável por vingança.",
    popularity: 1440.723,
    poster_path: "/vTtkQGC7qKlSRQJZYtAWAmYdH0A.jpg",
    release_date: "2021-11-05",
    title: "Dangerous",
    video: false,
    vote_average: 6.6,
    vote_count: 130,
  },
  {
    adult: false,
    backdrop_path: "/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg",
    genre_ids: [16, 28, 12, 14],
    id: 635302,
    original_language: "ja",
    original_title: "劇場版「鬼滅の刃」無限列車編",
    overview:
      "Tanjiro Kamado, junto com Inosuke Hashibira, um garoto criado por javalis que usa uma cabeça de javali, e Zenitsu Agatsuma, um garoto assustado que revela seu verdadeiro poder quando dorme, embarca no Trem Infinito em uma nova missão com o Hashira de Fogo, Kyojuro Rengoku, para derrotar um demônio que tem atormentado o povo e matado os caçadores de oni que se opõem a ele!",
    popularity: 1270.198,
    poster_path: "/yaX5hliSF1rwZ9WVNbUchndjFSb.jpg",
    release_date: "2020-10-16",
    title: "Demon Slayer - Mugen Train: O Filme",
    video: false,
    vote_average: 8.4,
    vote_count: 2088,
  },
  {
    adult: false,
    backdrop_path: "/A6K6Y39vYsYboyKiiXwcPR6Q6tM.jpg",
    genre_ids: [10770, 9648, 53, 35],
    id: 922885,
    original_language: "es",
    original_title: "Laura y el misterio del asesino inesperado",
    overview: "",
    popularity: 1266.084,
    poster_path: "/et361dUmgQeiqmlOi4o8zTUKfcs.jpg",
    release_date: "2022-01-13",
    title: "Laura y el misterio del asesino inesperado",
    video: false,
    vote_average: 7.3,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: "/qqthj8EUL4QKlDBoMcPqeWvi6Ya.jpg",
    genre_ids: [16, 14, 10402, 12, 35],
    id: 756403,
    original_language: "en",
    original_title: "Riverdance: The Animated Adventure",
    overview:
      "Um garoto irlandês chamado Keegan e uma garota espanhola chamada Moya viajam para o mundo mítico dos Megaloceros Giganteus, que os ensinam a apreciar Riverdance como uma celebração da vida. Inspirado pela sensação do palco global e com novas músicas do vencedor do Grammy Bill Whelan.",
    popularity: 1229.829,
    poster_path: "/i6TRDlVuuEXMyLSlIkDd8YhBN0r.jpg",
    release_date: "2021-05-28",
    title: "Riverdance: Uma Aventura Dançante",
    video: false,
    vote_average: 5.6,
    vote_count: 21,
  },
  {
    adult: false,
    backdrop_path: "/mv4lRdLy201m3pndE68MuIKofpt.jpg",
    genre_ids: [10749, 35],
    id: 790142,
    original_language: "en",
    original_title: "The Royal Treatment",
    overview:
      "A cabeleireira Izzy jamais perderia a chance de trabalhar no casamento de um príncipe encantado. Mas um clima entre os dois coloca o amor e o dever real na balança.",
    popularity: 1212.143,
    poster_path: "/g4myCGDieVwB9YSli5iFYiHBPNm.jpg",
    release_date: "2022-01-20",
    title: "Tratamento de Realeza",
    video: false,
    vote_average: 6.7,
    vote_count: 208,
  },
];
